### PR TITLE
Use <kbd> to mark keys

### PR DESCRIPTION
**Pull request by livibetter**

### CODE REVIEW

**Comment by livibetter** [comment]
By the way, what do you (@dhurum)  think about keys like <kbd>PgUp</kbd>/<kbd>PgDown</kbd> and <kbd>j</kbd>/<kbd>k</kbd> to flip pages?

**Comment by dhurum** [comment]
Thank you very much, I didn't know about this tag in github's markdown.

**Comment by dhurum** [comment]
Using <kbd>j</kbd>/<kbd>k</kbd> - great idea, will add right away.
<kbd>PgUp</kbd>/<kbd>PgDown</kbd> will require some additional work, I wasn't able to make ncurses work with redirected stdin yet, but I have a few ideas.

**Comment by dhurum** [comment]
<kbd>PgUp</kbd>/<kbd>PgDown</kbd> done in 7be9d275b7fb78086c2b31087f0115c01f53c6bd

**Pull request merged**
